-- AstroUI provides the basis for configuring the AstroNvim User Interface
-- Configuration documentation can be found with `:h astroui`
-- NOTE: We highly recommend setting up the Lua Language Server (`:LspInstall lua_ls`)
--       as this provides autocomplete and documentation while editing

---@type LazySpec
return {
  "AstroNvim/astroui",
  ---@type AstroUIOpts
  opts = {
    -- change colorscheme
    colorscheme = "astromars",
    -- AstroUI allows you to easily modify highlight groups easily for any and all colorschemes
    highlights = {
      init = { -- this table overrides highlights in all themes
        -- Keep syntax groups from the active colorscheme, only darken UI surfaces.
        Normal = { bg = "#0b0e14" },
        NormalNC = { bg = "#0b0e14" },
        NormalFloat = { bg = "#0f131a" },
        FloatBorder = { bg = "#0f131a", fg = "#3a4254" },
        WinSeparator = { bg = "#0b0e14", fg = "#1b2230" },
        VertSplit = { bg = "#0b0e14", fg = "#1b2230" },
        SignColumn = { bg = "#0b0e14" },
        EndOfBuffer = { bg = "#0b0e14", fg = "#0b0e14" },
        CursorLine = { bg = "#111722" },
        CursorLineNr = { fg = "#e6b450", bold = true },
        Visual = { bg = "#1a2333" },
        StatusLine = { bg = "#0f131a" },
        StatusLineNC = { bg = "#0b0e14" },
        TabLine = { bg = "#0f131a" },
        TabLineFill = { bg = "#0b0e14" },
        TabLineSel = { bg = "#1a2333", bold = true },
        WinBar = { bg = "#0f131a" },
        WinBarNC = { bg = "#0b0e14" },
        Pmenu = { bg = "#0b0e14" },
        PmenuSel = { bg = "#151c28" },
        PmenuSbar = { bg = "#151922" },
        PmenuThumb = { bg = "#323a4d" },
        NeoTreeNormal = { bg = "#0b0e14" },
        NeoTreeNormalNC = { bg = "#0b0e14" },
        NeoTreeEndOfBuffer = { bg = "#0b0e14", fg = "#0b0e14" },
        NeoTreeWinSeparator = { bg = "#0b0e14", fg = "#1b2230" },
        NeoTreeFloatBorder = { bg = "#0b0e14", fg = "#3a4254" },
        NeoTreeCursorLine = { bg = "#151c28" },
        NeoTreeTabActive = { bg = "#151c28", bold = true },
        NeoTreeTabInactive = { bg = "#0b0e14" },
        NeoTreeTabSeparatorActive = { bg = "#151c28", fg = "#1b2230" },
        NeoTreeTabSeparatorInactive = { bg = "#0b0e14", fg = "#1b2230" },
        NeoTreeTitleBar = { bg = "#151c28" },
        NeoTreeStatusLine = { bg = "#0b0e14" },
        NeoTreeStatusLineNC = { bg = "#0b0e14" },
        BlinkCmpMenu = { bg = "#0b0e14" },
        BlinkCmpMenuBorder = { bg = "#0b0e14", fg = "#3a4254" },
        BlinkCmpDoc = { bg = "#111722" },
        BlinkCmpDocBorder = { bg = "#111722", fg = "#3a4254" },
      },
      astromars = { -- enforce dark UI overrides specifically for the selected colorscheme
        Normal = { bg = "#0b0e14" },
        NormalNC = { bg = "#0b0e14" },
        NormalFloat = { bg = "#0f131a" },
        FloatBorder = { bg = "#0f131a", fg = "#3a4254" },
        WinSeparator = { bg = "#0b0e14", fg = "#1b2230" },
        VertSplit = { bg = "#0b0e14", fg = "#1b2230" },
        StatusLine = { bg = "#0f131a" },
        StatusLineNC = { bg = "#0b0e14" },
        TabLine = { bg = "#0f131a" },
        TabLineFill = { bg = "#0b0e14" },
        TabLineSel = { bg = "#1a2333", bold = true },
        WinBar = { bg = "#0f131a" },
        WinBarNC = { bg = "#0b0e14" },
        Pmenu = { bg = "#0b0e14" },
        PmenuSel = { bg = "#151c28" },
        PmenuSbar = { bg = "#0f131a" },
        PmenuThumb = { bg = "#323a4d" },
        BlinkCmpMenu = { bg = "#0b0e14" },
        BlinkCmpMenuBorder = { bg = "#0b0e14", fg = "#3a4254" },
        BlinkCmpDoc = { bg = "#0f131a" },
        BlinkCmpDocBorder = { bg = "#0f131a", fg = "#3a4254" },
        NeoTreeNormal = { bg = "#0b0e14" },
        NeoTreeNormalNC = { bg = "#0b0e14" },
        NeoTreeEndOfBuffer = { bg = "#0b0e14", fg = "#0b0e14" },
        NeoTreeWinSeparator = { bg = "#0b0e14", fg = "#1b2230" },
        NeoTreeFloatBorder = { bg = "#0b0e14", fg = "#3a4254" },
        NeoTreeCursorLine = { bg = "#151c28" },
        NeoTreeTabActive = { bg = "#151c28", bold = true },
        NeoTreeTabInactive = { bg = "#0b0e14" },
        NeoTreeTabSeparatorActive = { bg = "#151c28", fg = "#1b2230" },
        NeoTreeTabSeparatorInactive = { bg = "#0b0e14", fg = "#1b2230" },
        NeoTreeTitleBar = { bg = "#151c28" },
        NeoTreeStatusLine = { bg = "#0b0e14" },
        NeoTreeStatusLineNC = { bg = "#0b0e14" },
      },
      astrodark = { -- a table of overrides/changes when applying the astrotheme theme
        -- Normal = { bg = "#000000" },
      },
    },
    -- Icons can be configured throughout the interface
    icons = {
      -- configure the loading of the lsp in the status line
      LSPLoading1 = "⠋",
      LSPLoading2 = "⠙",
      LSPLoading3 = "⠹",
      LSPLoading4 = "⠸",
      LSPLoading5 = "⠼",
      LSPLoading6 = "⠴",
      LSPLoading7 = "⠦",
      LSPLoading8 = "⠧",
      LSPLoading9 = "⠇",
      LSPLoading10 = "⠏",
    },
  },
}
